// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniversityApp.Data;

#nullable disable

namespace UniversityApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UniversityApp.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Degree")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("Hrs")
                        .HasColumnType("int");

                    b.Property<decimal>("MinDegree")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Degree = 100m,
                            DepartmentId = 1,
                            Hrs = 3,
                            MinDegree = 50m,
                            Name = "Windows Programming"
                        },
                        new
                        {
                            Id = 2,
                            Degree = 100m,
                            DepartmentId = 1,
                            Hrs = 3,
                            MinDegree = 50m,
                            Name = "Database Systems"
                        },
                        new
                        {
                            Id = 3,
                            Degree = 100m,
                            DepartmentId = 2,
                            Hrs = 3,
                            MinDegree = 50m,
                            Name = "Web Development"
                        },
                        new
                        {
                            Id = 4,
                            Degree = 100m,
                            DepartmentId = 2,
                            Hrs = 3,
                            MinDegree = 50m,
                            Name = "Data Structures"
                        },
                        new
                        {
                            Id = 5,
                            Degree = 100m,
                            DepartmentId = 3,
                            Hrs = 3,
                            MinDegree = 50m,
                            Name = "Software Design"
                        });
                });

            modelBuilder.Entity("UniversityApp.Models.CrsResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CrsId")
                        .HasColumnType("int");

                    b.Property<decimal>("Degree")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("TraineeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CrsId");

                    b.HasIndex("TraineeId");

                    b.ToTable("CrsResults");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CrsId = 1,
                            Degree = 85m,
                            TraineeId = 1
                        },
                        new
                        {
                            Id = 2,
                            CrsId = 2,
                            Degree = 72m,
                            TraineeId = 1
                        },
                        new
                        {
                            Id = 3,
                            CrsId = 3,
                            Degree = 90m,
                            TraineeId = 2
                        },
                        new
                        {
                            Id = 4,
                            CrsId = 4,
                            Degree = 65m,
                            TraineeId = 2
                        },
                        new
                        {
                            Id = 5,
                            CrsId = 1,
                            Degree = 78m,
                            TraineeId = 3
                        });
                });

            modelBuilder.Entity("UniversityApp.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Manager")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Manager = "Dr. Ahmed Hassan",
                            Name = "Information Technology"
                        },
                        new
                        {
                            Id = 2,
                            Manager = "Dr. Sara Ali",
                            Name = "Computer Science"
                        },
                        new
                        {
                            Id = 3,
                            Manager = "Dr. Omar Khaled",
                            Name = "Software Engineering"
                        });
                });

            modelBuilder.Entity("UniversityApp.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("CrsId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CrsId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Alexandria, Egypt",
                            CrsId = 1,
                            DepartmentId = 1,
                            Email = "mahmoud@university.edu",
                            Name = "Mahmoud Alghonimy",
                            Salary = 8000m
                        },
                        new
                        {
                            Id = 2,
                            Address = "Cairo, Egypt",
                            CrsId = 3,
                            DepartmentId = 2,
                            Email = "sara@university.edu",
                            Name = "Sara Ali",
                            Salary = 7500m
                        },
                        new
                        {
                            Id = 3,
                            Address = "Giza, Egypt",
                            CrsId = 2,
                            DepartmentId = 1,
                            Email = "ahmed@university.edu",
                            Name = "Ahmed Mostafa",
                            Salary = 9000m
                        });
                });

            modelBuilder.Entity("UniversityApp.Models.Trainee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Trainees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Alexandria",
                            DepartmentId = 1,
                            Grade = "A",
                            Name = "Ali Hassan"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Cairo",
                            DepartmentId = 2,
                            Grade = "B",
                            Name = "Nour Mohamed"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Mansoura",
                            DepartmentId = 1,
                            Grade = "A",
                            Name = "Layla Ahmed"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Tanta",
                            DepartmentId = 3,
                            Grade = "C",
                            Name = "Omar Ibrahim"
                        });
                });

            modelBuilder.Entity("UniversityApp.Models.Course", b =>
                {
                    b.HasOne("UniversityApp.Models.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("UniversityApp.Models.CrsResult", b =>
                {
                    b.HasOne("UniversityApp.Models.Course", "Course")
                        .WithMany("CrsResults")
                        .HasForeignKey("CrsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversityApp.Models.Trainee", "Trainee")
                        .WithMany("CrsResults")
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("UniversityApp.Models.Instructor", b =>
                {
                    b.HasOne("UniversityApp.Models.Course", "Course")
                        .WithMany("Instructors")
                        .HasForeignKey("CrsId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UniversityApp.Models.Department", "Department")
                        .WithMany("Instructors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("UniversityApp.Models.Trainee", b =>
                {
                    b.HasOne("UniversityApp.Models.Department", "Department")
                        .WithMany("Trainees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("UniversityApp.Models.Course", b =>
                {
                    b.Navigation("CrsResults");

                    b.Navigation("Instructors");
                });

            modelBuilder.Entity("UniversityApp.Models.Department", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Instructors");

                    b.Navigation("Trainees");
                });

            modelBuilder.Entity("UniversityApp.Models.Trainee", b =>
                {
                    b.Navigation("CrsResults");
                });
#pragma warning restore 612, 618
        }
    }
}
